export const defaultKpis = [
  {
    id: "inc-01",
    kpi_id: "INC-01",
    name: "Number of Major Incidents",
    owner: "Sheila",
    module: "Incidents",
    dimension: "Priority / Major Incident",
    target: "<= 5",
    frequency: "Monthly",
    unit: "ticket",
    formula: "Count of major incidents opened in the month",
    source: "ServiceNow Incident",
    status: "Active",
    description: "Total number of major incidents requiring high-priority handling.",
  },
  {
    id: "inc-02",
    kpi_id: "INC-02",
    name: "Mean Elapsed Time for Incident Resolution",
    owner: "Ines",
    module: "Incidents",
    dimension: "Priority",
    target: "<= target by priority",
    frequency: "Monthly",
    unit: "hour",
    formula: "Average business resolve time by priority",
    source: "ServiceNow Incident",
    status: "Retired",
    description: "Average time to achieve incident resolution, historically broken down by priority.",
  },
  {
    id: "inc-03",
    kpi_id: "INC-03",
    name: "Number of Open Incidents (Backlog)",
    owner: "Sheila",
    module: "Incidents",
    dimension: "Backlog / State",
    target: "<= 624",
    frequency: "Monthly",
    unit: "ticket",
    formula: "Count of active incidents in backlog states",
    source: "ServiceNow Incident",
    status: "Active",
    description: "Current incident backlog volume across open operational states.",
  },
  {
    id: "inc-04",
    kpi_id: "INC-04",
    name: "Percentage of Incidents Closed by the Service Desk",
    owner: "Sheila",
    module: "Incidents",
    dimension: "Closure Efficiency",
    target: ">= 80%",
    frequency: "Monthly",
    unit: "%",
    formula: "Incidents closed by service desk / total eligible incidents",
    source: "ServiceNow Incident",
    status: "Retired",
    description: "Measures how many incidents are solved at first point of contact.",
  },
  {
    id: "inc-05",
    kpi_id: "INC-05",
    name: "Number of Incidents Resolved in 1 Hour",
    owner: "Sheila",
    module: "Incidents",
    dimension: "Resolution Speed",
    target: ">= target",
    frequency: "Monthly",
    unit: "ticket",
    formula: "Count of resolved incidents with duration <= 1 hour",
    source: "ServiceNow Incident",
    status: "Active",
    description: "Tracks fast resolution performance for incidents.",
  },
  {
    id: "inc-06",
    kpi_id: "INC-06",
    name: "Number of Incidents Created in a Month",
    owner: "Sheila",
    module: "Incidents",
    dimension: "Control KPI",
    target: "<= 1660",
    frequency: "Monthly",
    unit: "ticket",
    formula: "Count of incidents opened in the month",
    source: "ServiceNow Incident",
    status: "Active",
    description: "Control KPI used to monitor overall incident ticket volume trends.",
  },
  {
    id: "inc-07",
    kpi_id: "INC-07",
    name: "Size of Current Incident Backlog by IT Service",
    owner: "Sheila",
    module: "Incidents",
    dimension: "IT Service",
    target: "Drill down",
    frequency: "Monthly",
    unit: "ticket",
    formula: "Count of active incidents grouped by service",
    source: "ServiceNow Incident",
    status: "Active",
    description: "Shows which IT services carry the largest active incident backlog.",
  },
  {
    id: "inc-08",
    kpi_id: "INC-08",
    name: "Number of Major Incidents by IT Service",
    owner: "Sheila",
    module: "Incidents",
    dimension: "IT Service",
    target: "Drill down",
    frequency: "Monthly",
    unit: "ticket",
    formula: "Count of major incidents grouped by service",
    source: "ServiceNow Incident",
    status: "Active",
    description: "Highlights services most affected by major incidents.",
  },
  {
    id: "inc-09",
    kpi_id: "INC-09",
    name: "Number of Past Due Incidents (Response)",
    owner: "Sheila",
    module: "Incidents",
    dimension: "SLA Response",
    target: "<= 331",
    frequency: "Monthly",
    unit: "ticket",
    formula: "Count of incidents breaching response SLA",
    source: "ServiceNow Task SLA",
    status: "Active",
    description: "Measures incidents that missed the response SLA target.",
  },
  {
    id: "inc-12",
    kpi_id: "INC-12",
    name: "Incident Resolution Time Compliance Rate",
    owner: "Sheila",
    module: "Incidents",
    dimension: "SLA Resolution",
    target: ">= 80%",
    frequency: "Monthly",
    unit: "%",
    formula: "(Incidents within resolution SLA / resolved incidents) * 100",
    source: "ServiceNow Task SLA",
    status: "Active",
    description: "Percentage of resolved incidents completed within resolution SLA.",
  },
  {
    id: "inc-13",
    kpi_id: "INC-13",
    name: "Incident First Response Time Compliance Rate",
    owner: "Sheila",
    module: "Incidents",
    dimension: "SLA Response",
    target: ">= 80%",
    frequency: "Monthly",
    unit: "%",
    formula: "(Incidents within response SLA / total incidents) * 100",
    source: "ServiceNow Task SLA",
    status: "Active",
    description: "Percentage of incidents answered within the response SLA window.",
  },
  {
    id: "inc-15",
    kpi_id: "INC-15",
    name: "Number of Past Due Incidents (Resolution)",
    owner: "Sheila",
    module: "Incidents",
    dimension: "SLA Resolution",
    target: "<= target",
    frequency: "Monthly",
    unit: "ticket",
    formula: "Count of incidents breaching resolution SLA",
    source: "ServiceNow Task SLA",
    status: "Active",
    description: "Measures incidents that missed the resolution SLA target.",
  },
  {
    id: "req-01",
    kpi_id: "REQ-01",
    name: "Number of Open Service Requests (Backlog)",
    owner: "Lassaad",
    module: "Requests",
    dimension: "Backlog / Aging",
    target: "<= target",
    frequency: "Monthly",
    unit: "request",
    formula: "Count of requests still open or work in progress",
    source: "ServiceNow Request",
    status: "Active",
    description: "Current request backlog volume, including aging focus for overdue demand.",
  },
  {
    id: "req-02",
    kpi_id: "REQ-02",
    name: "Number of Closed Requests",
    owner: "Lassaad",
    module: "Requests",
    dimension: "Closure Volume",
    target: ">= target",
    frequency: "Monthly",
    unit: "request",
    formula: "Count of requests closed in the month",
    source: "ServiceNow Request",
    status: "Active",
    description: "Measures closure throughput for service requests.",
  },
  {
    id: "req-03",
    kpi_id: "REQ-03",
    name: "Number of Requests Created in a Month",
    owner: "Lassaad",
    module: "Requests",
    dimension: "Control KPI",
    target: "<= target",
    frequency: "Monthly",
    unit: "request",
    formula: "Count of requests opened in the month",
    source: "ServiceNow Request",
    status: "Active",
    description: "Control KPI used to monitor service request ticket volume trends.",
  },
  {
    id: "req-04",
    kpi_id: "REQ-04",
    name: "Request Backlog Aging Over 60 Days",
    owner: "Lassaad",
    module: "Requests",
    dimension: "Aging",
    target: "0",
    frequency: "Monthly",
    unit: "request",
    formula: "Count of open requests older than 60 days",
    source: "ServiceNow Request",
    status: "Active",
    description: "Highlights old requests that remain in backlog beyond 60 days.",
  },
  {
    id: "req-05",
    kpi_id: "REQ-05",
    name: "Request Closure Rate",
    owner: "Lassaad",
    module: "Requests",
    dimension: "Closure Efficiency",
    target: ">= target",
    frequency: "Monthly",
    unit: "%",
    formula: "(Closed requests / total requests) * 100",
    source: "ServiceNow Request",
    status: "Active",
    description: "Percentage of requests closed within the observed reporting scope.",
  },
  {
    id: "req-06",
    kpi_id: "REQ-06",
    name: "Requests by Business Service",
    owner: "Lassaad",
    module: "Requests",
    dimension: "Business Service",
    target: "Drill down",
    frequency: "Monthly",
    unit: "request",
    formula: "Count of requests grouped by IT service or business service",
    source: "ServiceNow Request",
    status: "Active",
    description: "Deep dive KPI used to identify where request demand is concentrated.",
  },
  {
    id: "chg-01",
    kpi_id: "CHG-01",
    name: "Number of Past Due Changes",
    owner: "Khrystyna",
    module: "Changes",
    dimension: "Schedule Compliance",
    target: "<= 1028",
    frequency: "Monthly",
    unit: "change",
    formula: "Count of changes not implemented according to planned dates",
    source: "ServiceNow Change",
    status: "Active",
    description: "Measures changes that passed planned due date without timely implementation.",
  },
  {
    id: "chg-02",
    kpi_id: "CHG-02",
    name: "Number of Critical Changes",
    owner: "Karen",
    module: "Changes",
    dimension: "Priority",
    target: "<= target",
    frequency: "Monthly",
    unit: "change",
    formula: "Count of changes marked critical",
    source: "ServiceNow Change",
    status: "Active",
    description: "Shows critical changes requiring extra attention and earlier closure.",
  },
  {
    id: "chg-03",
    kpi_id: "CHG-03",
    name: "Number of Changes Created in a Month",
    owner: "Martin",
    module: "Changes",
    dimension: "Control KPI",
    target: "<= target",
    frequency: "Monthly",
    unit: "change",
    formula: "Count of changes opened in the month",
    source: "ServiceNow Change",
    status: "Active",
    description: "Control KPI used to monitor overall monthly change volume.",
  },
  {
    id: "chg-04",
    kpi_id: "CHG-04",
    name: "Number of Emergency Changes",
    owner: "Martin",
    module: "Changes",
    dimension: "Emergency Type",
    target: "<= target",
    frequency: "Monthly",
    unit: "change",
    formula: "Count of emergency changes in the month",
    source: "ServiceNow Change",
    status: "Active",
    description: "Shows remediation changes that must be introduced as soon as possible.",
  },
  {
    id: "chg-05",
    kpi_id: "CHG-05",
    name: "Closed Changes Percentage",
    owner: "Karen",
    module: "Changes",
    dimension: "Closure Efficiency",
    target: ">= target",
    frequency: "Monthly",
    unit: "%",
    formula: "(Closed changes / total changes) * 100",
    source: "ServiceNow Change",
    status: "Active",
    description: "Percentage of changes completed and closed during the reporting period.",
  },
  {
    id: "chg-06",
    kpi_id: "CHG-06",
    name: "Number of Open Changes (Backlog)",
    owner: "Khrystyna",
    module: "Changes",
    dimension: "Backlog",
    target: "<= target",
    frequency: "Monthly",
    unit: "change",
    formula: "Count of changes still open across active states",
    source: "ServiceNow Change",
    status: "Active",
    description: "Tracks the size of the current change backlog.",
  },
];

export function mergeWithDefaultKpis(customKpis = []) {
  const byKpiId = new Map(defaultKpis.map((item) => [item.kpi_id, item]));

  customKpis.forEach((item) => {
    byKpiId.set(item.kpi_id || String(item.id), item);
  });

  return Array.from(byKpiId.values());
}
