export const MOCK_CHANGES = [
  {
    id: 1,
    count: 1,
    number: "CHG-3001",
    type: "Normal",
    state: "Closed",
    priority: "P2",
    affected_service: "ERP",
    parent: "",
    service_owner: "Applications Team",
    configuration_item: "SAP Production",
    location: "Sfax Plant",
    description: "Deploy ERP patch for performance improvement.",
    short_description: "ERP patch deployment",
    opened: "2026-02-20 09:00",
    planned_start_date: "2026-02-22 20:00",
    planned_end_date: "2026-02-22 22:00",
    closed: "2026-02-22 22:15",
    responsible_group: "Change Management",
    responsible_user: "Wiem Ben Romdhane",
    location_division: "Manufacturing",
    service_classification: "Business Application",
    risk: "Medium",
    category: "Application",
    close_code: "Successful",
    close_notes: "Deployment completed successfully with validation.",
  },
  {
    id: 2,
    count: 1,
    number: "CHG-3002",
    type: "Emergency",
    state: "Closed",
    priority: "P1",
    affected_service: "Network",
    parent: "",
    service_owner: "Infrastructure Team",
    configuration_item: "Core Switch",
    location: "Tunis HQ",
    description: "Urgent network change to restore connectivity.",
    short_description: "Emergency switch reconfiguration",
    opened: "2026-03-01 07:30",
    planned_start_date: "2026-03-01 08:00",
    planned_end_date: "2026-03-01 08:45",
    closed: "2026-03-01 08:40",
    responsible_group: "Network",
    responsible_user: "Rami Hadded",
    location_division: "Corporate",
    service_classification: "Infrastructure",
    risk: "High",
    category: "Network",
    close_code: "Successful",
    close_notes: "Traffic restored after rollback and reconfiguration.",
  },
  {
    id: 3,
    count: 1,
    number: "CHG-3003",
    type: "Standard",
    state: "Scheduled",
    priority: "P3",
    affected_service: "Email",
    parent: "",
    service_owner: "Messaging Team",
    configuration_item: "Exchange Online Policy",
    location: "Remote",
    description: "Mailbox retention policy update.",
    short_description: "Retention policy update",
    opened: "2026-03-03 10:10",
    planned_start_date: "2026-03-06 18:00",
    planned_end_date: "2026-03-06 19:00",
    closed: "",
    responsible_group: "Messaging",
    responsible_user: "Ahmed Trabelsi",
    location_division: "Corporate",
    service_classification: "Collaboration Service",
    risk: "Low",
    category: "Messaging",
    close_code: "",
    close_notes: "",
  },
  {
    id: 4,
    count: 1,
    number: "CHG-3004",
    type: "Normal",
    state: "Implementation",
    priority: "P2",
    affected_service: "VPN",
    parent: "",
    service_owner: "Infrastructure Team",
    configuration_item: "VPN Gateway",
    location: "Sousse Site",
    description: "Upgrade VPN gateway firmware.",
    short_description: "VPN firmware upgrade",
    opened: "2026-03-04 13:20",
    planned_start_date: "2026-03-07 21:00",
    planned_end_date: "2026-03-07 22:00",
    closed: "",
    responsible_group: "Network",
    responsible_user: "Mohamed Gharbi",
    location_division: "Production",
    service_classification: "Infrastructure",
    risk: "Medium",
    category: "Network",
    close_code: "",
    close_notes: "",
  },
  {
    id: 5,
    count: 1,
    number: "CHG-3005",
    type: "Standard",
    state: "Closed",
    priority: "P4",
    affected_service: "Printer Service",
    parent: "",
    service_owner: "End User Computing",
    configuration_item: "Print Server",
    location: "Warehouse",
    description: "Add new printer queue for warehouse label printer.",
    short_description: "New printer queue creation",
    opened: "2026-02-18 08:40",
    planned_start_date: "2026-02-19 07:00",
    planned_end_date: "2026-02-19 07:30",
    closed: "2026-02-19 07:25",
    responsible_group: "Workplace Support",
    responsible_user: "Nader Ben Amor",
    location_division: "Logistics",
    service_classification: "End User Service",
    risk: "Low",
    category: "Workplace",
    close_code: "Successful",
    close_notes: "Queue created and tested successfully.",
  },
];