# Generated by Django 5.2.15 on 2026-06-29 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itsm_data', '0013_cleanup_userprofile_birth_columns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='change',
            name='category',
        ),
    ]
