# Generated by Django 5.2.15 on 2026-06-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsm_data', '0014_remove_change_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='change',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
