# Generated by Django 5.2.15 on 2026-06-29 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itsm_data', '0015_change_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='change',
            name='priority',
        ),
    ]
