# Generated by Django 5.2.15 on 2026-06-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsm_data', '0016_remove_change_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='change',
            name='priority',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
