# Generated by Django 5.2.15 on 2026-06-29 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itsm_data', '0017_change_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpidefinition',
            name='dimension',
        ),
    ]
