export const MOCK_INCIDENTS = [
  {
    id: 1,
    number: "INC-1001",
    state: "Open",
    priority: "P1",
    affected_service: "Email",
    parent: "",
    parent_incident: "",
    service_owner: "Messaging Team",
    configuration_item: "Exchange Server",
    location: "Tunis HQ",
    description: "Users cannot send emails from Outlook since this morning.",
    short_description: "Email outage affecting multiple users",
    opened: "2026-03-01 08:30",
    resolution_code: "",
    resolution_notes: "",
    responsible_group: "Service Desk",
    responsible_user: "Ahmed Trabelsi",
    resolved: "",
    reopen_count: 1,
    caller: "Fatma Ben Ali",
    aging_group: "0-2 days",
    duration: 180,
    service_classification: "Business Critical",
    business_duration: 140,
    problem: "PRB-101",
    sla: "Gold",
    schedule: "24x7",
    location_division: "Corporate",
    service_request: "",
    is_major: true,
    sla_breached: true,
  },
  {
    id: 2,
    number: "INC-1002",
    state: "Resolved",
    priority: "P2",
    affected_service: "VPN",
    parent: "",
    parent_incident: "",
    service_owner: "Infrastructure Team",
    configuration_item: "VPN Gateway",
    location: "Sousse Site",
    description: "Remote users reported intermittent VPN disconnections.",
    short_description: "VPN instability for remote users",
    opened: "2026-03-02 10:00",
    resolution_code: "Solved Remotely",
    resolution_notes: "Restarted VPN service and applied config patch.",
    responsible_group: "Network",
    responsible_user: "Mohamed Gharbi",
    resolved: "2026-03-02 14:15",
    reopen_count: 0,
    caller: "Sami Jlassi",
    aging_group: "0-2 days",
    duration: 255,
    service_classification: "Infrastructure",
    business_duration: 210,
    problem: "",
    sla: "Silver",
    schedule: "Business Hours",
    location_division: "Production",
    service_request: "",
    is_major: false,
    sla_breached: false,
  },
  {
    id: 3,
    number: "INC-1003",
    state: "Closed",
    priority: "P3",
    affected_service: "ERP",
    parent: "",
    parent_incident: "",
    service_owner: "Applications Team",
    configuration_item: "SAP App Node",
    location: "Sfax Plant",
    description: "Purchase order screen loading slowly for several users.",
    short_description: "ERP performance degradation",
    opened: "2026-02-25 09:10",
    resolution_code: "Permanent Fix",
    resolution_notes: "Optimized DB query and cleared cache.",
    responsible_group: "Application Support",
    responsible_user: "Wiem Ben Romdhane",
    resolved: "2026-02-25 16:40",
    reopen_count: 0,
    caller: "Ons Kefi",
    aging_group: "0-2 days",
    duration: 450,
    service_classification: "Business Application",
    business_duration: 390,
    problem: "PRB-087",
    sla: "Silver",
    schedule: "Business Hours",
    location_division: "Manufacturing",
    service_request: "REQ-3021",
    is_major: false,
    sla_breached: false,
  },
  {
    id: 4,
    number: "INC-1004",
    state: "In Progress",
    priority: "P2",
    affected_service: "Wi-Fi",
    parent: "",
    parent_incident: "",
    service_owner: "Infrastructure Team",
    configuration_item: "Wireless Controller",
    location: "Tunis HQ",
    description: "Users in meeting rooms cannot connect to corporate Wi-Fi.",
    short_description: "Wi-Fi issue in meeting rooms",
    opened: "2026-03-03 11:20",
    resolution_code: "",
    resolution_notes: "",
    responsible_group: "Network",
    responsible_user: "Rami Hadded",
    resolved: "",
    reopen_count: 0,
    caller: "Nour Hajji",
    aging_group: "0-2 days",
    duration: 95,
    service_classification: "Infrastructure",
    business_duration: 80,
    problem: "",
    sla: "Gold",
    schedule: "24x7",
    location_division: "Corporate",
    service_request: "",
    is_major: false,
    sla_breached: false,
  },
  {
    id: 5,
    number: "INC-1005",
    state: "Open",
    priority: "P1",
    affected_service: "Service Desk",
    parent: "",
    parent_incident: "INC-1001",
    service_owner: "IT Operations",
    configuration_item: "Ticketing Portal",
    location: "Remote",
    description: "Users unable to create incidents on portal.",
    short_description: "Ticketing portal unavailable",
    opened: "2026-03-04 07:45",
    resolution_code: "",
    resolution_notes: "",
    responsible_group: "Platform Support",
    responsible_user: "Yassine Mzoughi",
    resolved: "",
    reopen_count: 0,
    caller: "Helpdesk Agent",
    aging_group: "0-2 days",
    duration: 60,
    service_classification: "Core IT",
    business_duration: 55,
    problem: "",
    sla: "Gold",
    schedule: "24x7",
    location_division: "Corporate",
    service_request: "",
    is_major: true,
    sla_breached: false,
  },
];