export const MOCK_REQUESTS = [
  {
    id: 1,
    count: 1,
    number: "REQ-2001",
    state: "Open",
    item: "Laptop Request",
    short_description: "New laptop for finance user",
    description: "Request for a new laptop due to device replacement.",
    affected_service: "Workplace",
    parent: "",
    service_owner: "End User Computing",
    request: "Standard Request",
    requested_for: "Amira Ben Salah",
    opened: "2026-03-01 09:00",
    opened_by: "Helpdesk Agent",
    responsible_group: "Service Desk",
    responsible_user: "Sarra Khelifi",
    location: "Tunis HQ",
    aging_group: "0-2 days",
    location_division: "Corporate",
    updated: "2026-03-01 11:30",
    resolve_time: "",
    service_classification: "End User Service",
    closed: "",
    closed_by: "",
    it_service: "Laptop Service",
  },
  {
    id: 2,
    count: 1,
    number: "REQ-2002",
    state: "In Progress",
    item: "VPN Access",
    short_description: "VPN access for remote employee",
    description: "User needs VPN access for remote work.",
    affected_service: "Network",
    parent: "",
    service_owner: "Infrastructure Team",
    request: "Access Request",
    requested_for: "Youssef Triki",
    opened: "2026-03-02 08:15",
    opened_by: "Self Service Portal",
    responsible_group: "Network",
    responsible_user: "Rami Hadded",
    location: "Sousse Site",
    aging_group: "0-2 days",
    location_division: "Production",
    updated: "2026-03-02 14:00",
    resolve_time: "",
    service_classification: "Access Management",
    closed: "",
    closed_by: "",
    it_service: "VPN",
  },
  {
    id: 3,
    count: 1,
    number: "REQ-2003",
    state: "Closed",
    item: "SAP Access",
    short_description: "Access request to SAP purchasing module",
    description: "Purchasing team member needs access to SAP MM module.",
    affected_service: "ERP",
    parent: "",
    service_owner: "Applications Team",
    request: "Access Request",
    requested_for: "Mariem Gharbi",
    opened: "2026-02-26 10:20",
    opened_by: "Manager Approval",
    responsible_group: "Application Support",
    responsible_user: "Wiem Ben Romdhane",
    location: "Sfax Plant",
    aging_group: "2-5 days",
    location_division: "Manufacturing",
    updated: "2026-02-27 09:10",
    resolve_time: "1 day",
    service_classification: "Business Application",
    closed: "2026-02-27 09:15",
    closed_by: "Wiem Ben Romdhane",
    it_service: "SAP",
  },
  {
    id: 4,
    count: 1,
    number: "REQ-2004",
    state: "Open",
    item: "Shared Mailbox",
    short_description: "Create shared mailbox for HR team",
    description: "Need a shared mailbox for HR operations.",
    affected_service: "Email",
    parent: "",
    service_owner: "Messaging Team",
    request: "Standard Request",
    requested_for: "HR Department",
    opened: "2026-03-03 13:05",
    opened_by: "Self Service Portal",
    responsible_group: "Messaging",
    responsible_user: "Ahmed Trabelsi",
    location: "Tunis HQ",
    aging_group: "0-2 days",
    location_division: "Corporate",
    updated: "2026-03-03 16:45",
    resolve_time: "",
    service_classification: "Collaboration Service",
    closed: "",
    closed_by: "",
    it_service: "Email",
  },
  {
    id: 5,
    count: 1,
    number: "REQ-2005",
    state: "Closed",
    item: "Printer Access",
    short_description: "Map printer for warehouse team",
    description: "Printer mapping request for new workstation in warehouse.",
    affected_service: "Printing",
    parent: "",
    service_owner: "End User Computing",
    request: "Standard Request",
    requested_for: "Warehouse User",
    opened: "2026-02-24 07:50",
    opened_by: "Helpdesk Agent",
    responsible_group: "Workplace Support",
    responsible_user: "Nader Ben Amor",
    location: "Sousse Warehouse",
    aging_group: "2-5 days",
    location_division: "Logistics",
    updated: "2026-02-24 12:10",
    resolve_time: "4 hours",
    service_classification: "End User Service",
    closed: "2026-02-24 12:20",
    closed_by: "Nader Ben Amor",
    it_service: "Printer Service",
  },
];